//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SermonPodcastPages.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\graha\\OneDrive\\Documents\\XL\\SermonPodcast.xlsx")]
        public string SpreadsheetLocation {
            get {
                return ((string)(this["SpreadsheetLocation"]));
            }
            set {
                this["SpreadsheetLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\graha\\Documents\\Sermon podcasts\\MP3")]
        public string LocalDriveLocation {
            get {
                return ((string)(this["LocalDriveLocation"]));
            }
            set {
                this["LocalDriveLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://a03dda5ab985dca85402cdbefe49ac91faf71a03.googledrive.com/host/0Bzf9aI-ZNy" +
            "1GUkk3Y2g1SmU0bG8")]
        public string NetworkDriveLocation {
            get {
                return ((string)(this["NetworkDriveLocation"]));
            }
            set {
                this["NetworkDriveLocation"] = value;
            }
        }
    }
}
